version: "3.7"
services:
    web:
      image: registry.gitlab.com/1337its/projects/bkwire/dev-nginx:latest
      restart: unless-stopped
      tty: true
      volumes:
        - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - flaskapi
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    flaskapi:
      image: registry.gitlab.com/1337its/projects/bkwire/dev-flask_api:latest
      restart: unless-stopped
      tty: true
      container_name: flask-api
      hostname: flask-api
      command: uwsgi --ini /app/uwsgi.ini
      volumes:
        - ./docker/flask_api:/script/data

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
